### Q1. Write a Python Program to Add Two Matrices?

In [7]:
import numpy as np
def add_mat(a, b):
    c= np.add(a,b)
    print(c)

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[2,3,5],[1,1,1],[2,2,2]])
add_mat(a,b)

[[ 3  5  8]
 [ 5  6  7]
 [ 9 10 11]]


### Q2. Write a Python Program to Multiply Two Matrices?

In [10]:
import numpy as np
def mat_mul(a,b):
    c = a@b
    print(c)
    
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[2,3,5],[1,1,1],[2,2,2]])
mat_mul(a,b)

[[10 11 13]
 [25 29 37]
 [40 47 61]]


### Q3. Write a Python Program to Transpose a Matrix?

In [12]:
def mat_trans(a):
    c = a.T
    print(c)
    
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat_trans(a)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Q4. Write a Python Program to Sort Words in Alphabetic Order?

In [13]:
def sortString(ss):
    in_string = ss
    sorted_list = sorted(in_string.split(' '))
    print(' '.join(sorted_list))

sortString("current assignment is number four")

assignment current four is number


### Q5. Write a Python Program to Remove Punctuation From a String?

In [15]:
def removePunctuatuions(ss):
    punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    in_string = ss
    out_string = ''
    for ele in in_string:
        if ele not in punctuations:
            out_string += ele
    print(out_string)
    
ss = "where's the ball !!!"
removePunctuatuions(ss)

wheres the ball 
